### ISSUE TITLE
for key in data["data"]:

### ISSUE THREAD

**Issue by snowcrash-arin** [mlo40/VsPyYt#5]
Hi,

I'm having issue with line # 29 in vsyt.py file. Could you tell me where you're referencing the data?  

Getting this.

VsPyYt-main/vsyt.py", line 28, in main
    for key in data["data"]:
NameError: name 'data' is not defined

**Comment by mlo40** [comment]
Ah that's some crusty old code, replace data["data"] with cmm['COMMANDS'] and chat = LiveChat(video_id=op) with chat = pytchat.create(video_id=op).

cmm['COMMANDS'] is the commands being loaded from the .ini file, used both for checking if the sent msg is a command and for executing the command.
Seen in line 30 and line 37.
cmm it self is defined form calling the function setup which is defined in setup.py, setup handles the authentication and file generation soo while it still has the file data it just passes it on to the main code using return config

note i have added the changes to the repo now

**Comment by mlo40** [comment]
Just in case the code still doesn't work I will leave this open for a bit

**Comment by snowcrash-arin** [comment]
Your project has been incredibly helpful as I begin working on VTube Studio. Thank you!

I'll test it today and let you know.

**Comment by snowcrash-arin** [comment]
So I'm getting this.  Any idea?

`2023-01-13 20:00:54 [user1]- !spin
!spin
Traceback (most recent call last):
  File "/Downloads/VsPyYt-main/./vsyt.py", line 39, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Downloads/VsPyYt-main/./vsyt.py", line 32, in main
    mdinf = await getmd(websocket)
  File "/Downloads/VsPyYt-main/func.py", line 69, in getmd
    json_data = await websocket.recv()
  File "/.virtualenvs/VsPyYt-main/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/.virtualenvs/VsPyYt-main/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1002 (protocol error); then sent 1002 (protocol error)
`

**Comment by mlo40** [comment]
Soo for some reason the code or VTube studio api is a a bit iffy about what you do first I recommend trying to change model use !wanko and then stuf like spin after that it shouldn't matter what avatar you have
